package com.tl.resource.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.tl.resource.dao.pojo.CompanyReports;
import com.tl.resource.dao.pojo.CompanyReportsExample;

public class CompanyReportsDAOImpl extends SqlMapClientDaoSupport implements CompanyReportsDAO {

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public CompanyReportsDAOImpl() {
    super();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public void insert(CompanyReports record) {
    getSqlMapClientTemplate().insert("company_reports.abatorgenerated_insert", record);
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int updateByPrimaryKeyWithoutBLOBs(CompanyReports record) {
    int rows = getSqlMapClientTemplate().update("company_reports.abatorgenerated_updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int updateByPrimaryKeyWithBLOBs(CompanyReports record) {
    int rows = getSqlMapClientTemplate().update("company_reports.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int updateByPrimaryKeySelective(CompanyReports record) {
    int rows = getSqlMapClientTemplate().update("company_reports.abatorgenerated_updateByPrimaryKeySelective", record);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public List selectByExampleWithoutBLOBs(CompanyReportsExample example) {
    List list = getSqlMapClientTemplate().queryForList("company_reports.abatorgenerated_selectByExample", example);
    return list;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public List selectByExampleWithBLOBs(CompanyReportsExample example) {
    List list = getSqlMapClientTemplate().queryForList("company_reports.abatorgenerated_selectByExampleWithBLOBs", example);
    return list;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public CompanyReports selectByPrimaryKey(String id) {
    CompanyReports key = new CompanyReports();
    key.setId(id);
    CompanyReports record = (CompanyReports) getSqlMapClientTemplate().queryForObject("company_reports.abatorgenerated_selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int deleteByExample(CompanyReportsExample example) {
    int rows = getSqlMapClientTemplate().delete("company_reports.abatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int deleteByPrimaryKey(String id) {
    CompanyReports key = new CompanyReports();
    key.setId(id);
    int rows = getSqlMapClientTemplate().delete("company_reports.abatorgenerated_deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int countByExample(CompanyReportsExample example) {
    Integer count = (Integer) getSqlMapClientTemplate().queryForObject("company_reports.abatorgenerated_countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int updateByExampleSelective(CompanyReports record, CompanyReportsExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("company_reports.abatorgenerated_updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int updateByExampleWithBLOBs(CompanyReports record, CompanyReportsExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("company_reports.abatorgenerated_updateByExampleWithBLOBs", parms);
    return rows;
  }

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  public int updateByExampleWithoutBLOBs(CompanyReports record, CompanyReportsExample example) {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = getSqlMapClientTemplate().update("company_reports.abatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This class was generated by Abator for iBATIS.
   * This class corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  private static class UpdateByExampleParms extends CompanyReportsExample {
    private Object record;

    public UpdateByExampleParms(Object record, CompanyReportsExample example) {
      super(example);
      this.record = record;
    }

    public Object getRecord() {
      return record;
    }
  }

  @Override
  public CompanyReports getReportLast() {
    CompanyReports record = (CompanyReports) getSqlMapClientTemplate().queryForObject("company_reports.getReportLast", null);
    return record;
  }
}