package com.tl.resource.dao;

import java.util.List;

import com.tl.resource.dao.pojo.CompanyReports;
import com.tl.resource.dao.pojo.CompanyReportsExample;

public interface CompanyReportsDAO {
  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  void insert(CompanyReports record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int updateByPrimaryKeyWithoutBLOBs(CompanyReports record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int updateByPrimaryKeyWithBLOBs(CompanyReports record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int updateByPrimaryKeySelective(CompanyReports record);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  List selectByExampleWithoutBLOBs(CompanyReportsExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  List selectByExampleWithBLOBs(CompanyReportsExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  CompanyReports selectByPrimaryKey(String id);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int deleteByExample(CompanyReportsExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int countByExample(CompanyReportsExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int updateByExampleSelective(CompanyReports record, CompanyReportsExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int updateByExampleWithBLOBs(CompanyReports record, CompanyReportsExample example);

  /**
   * This method was generated by Abator for iBATIS.
   * This method corresponds to the database table company_reports
   *
   * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
   */
  int updateByExampleWithoutBLOBs(CompanyReports record, CompanyReportsExample example);

  CompanyReports getReportLast();
}