package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TExpTemplete;
import com.tl.resource.dao.pojo.TExpTempleteExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TExpTempleteDAOImpl extends SqlMapClientDaoSupport implements TExpTempleteDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public TExpTempleteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public void insert(TExpTemplete record) {
        getSqlMapClientTemplate().insert("t_exp_templete.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public int updateByPrimaryKey(TExpTemplete record) {
        int rows = getSqlMapClientTemplate().update("t_exp_templete.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public int updateByPrimaryKeySelective(TExpTemplete record) {
        int rows = getSqlMapClientTemplate().update("t_exp_templete.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public List selectByExample(TExpTempleteExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_exp_templete.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public TExpTemplete selectByPrimaryKey(String id) {
        TExpTemplete key = new TExpTemplete();
        key.setId(id);
        TExpTemplete record = (TExpTemplete) getSqlMapClientTemplate().queryForObject("t_exp_templete.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public int deleteByExample(TExpTempleteExample example) {
        int rows = getSqlMapClientTemplate().delete("t_exp_templete.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public int deleteByPrimaryKey(String id) {
        TExpTemplete key = new TExpTemplete();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_exp_templete.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public int countByExample(TExpTempleteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_exp_templete.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public int updateByExampleSelective(TExpTemplete record, TExpTempleteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_exp_templete.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    public int updateByExample(TExpTemplete record, TExpTempleteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_exp_templete.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_exp_templete
     *
     * @abatorgenerated Sun May 01 10:00:23 CST 2011
     */
    private static class UpdateByExampleParms extends TExpTempleteExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExpTempleteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}