package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TExpTemplete;
import com.tl.resource.dao.pojo.TExpTempleteExample;
import java.util.List;

public interface TExpTempleteDAO {

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  void insert(TExpTemplete record);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  int updateByPrimaryKey(TExpTemplete record);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  int updateByPrimaryKeySelective(TExpTemplete record);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  List selectByExample(TExpTempleteExample example);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  TExpTemplete selectByPrimaryKey(String id);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  int deleteByExample(TExpTempleteExample example);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  int countByExample(TExpTempleteExample example);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  int updateByExampleSelective(TExpTemplete record, TExpTempleteExample example);

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  int updateByExample(TExpTemplete record, TExpTempleteExample example);
}