package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TExpTempleteType;
import com.tl.resource.dao.pojo.TExpTempleteTypeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TExpTempleteTypeDAOImpl extends SqlMapClientDaoSupport implements TExpTempleteTypeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public TExpTempleteTypeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public void insert(TExpTempleteType record) {
        getSqlMapClientTemplate().insert("t_exp_templete_type.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public int updateByPrimaryKey(TExpTempleteType record) {
        int rows = getSqlMapClientTemplate().update("t_exp_templete_type.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public int updateByPrimaryKeySelective(TExpTempleteType record) {
        int rows = getSqlMapClientTemplate().update("t_exp_templete_type.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public List selectByExample(TExpTempleteTypeExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_exp_templete_type.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public TExpTempleteType selectByPrimaryKey(Integer id) {
        TExpTempleteType key = new TExpTempleteType();
        key.setId(id);
        TExpTempleteType record = (TExpTempleteType) getSqlMapClientTemplate().queryForObject("t_exp_templete_type.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public int deleteByExample(TExpTempleteTypeExample example) {
        int rows = getSqlMapClientTemplate().delete("t_exp_templete_type.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        TExpTempleteType key = new TExpTempleteType();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_exp_templete_type.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public int countByExample(TExpTempleteTypeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_exp_templete_type.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public int updateByExampleSelective(TExpTempleteType record, TExpTempleteTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_exp_templete_type.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public int updateByExample(TExpTempleteType record, TExpTempleteTypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_exp_templete_type.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    private static class UpdateByExampleParms extends TExpTempleteTypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, TExpTempleteTypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}