package  com.tl.resource.dao;

import com.tl.resource.dao.pojo.TForum;
import com.tl.resource.dao.pojo.TForumExample;
import java.util.List;

public interface TForumDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int countByExample(TForumExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int deleteByExample(TForumExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    void insert(TForum record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    void insertSelective(TForum record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    List selectByExampleWithBLOBs(TForumExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    List selectByExampleWithoutBLOBs(TForumExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    TForum selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int updateByExampleSelective(TForum record, TForumExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int updateByExampleWithBLOBs(TForum record, TForumExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int updateByExampleWithoutBLOBs(TForum record, TForumExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int updateByPrimaryKeySelective(TForum record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(TForum record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    int updateByPrimaryKeyWithoutBLOBs(TForum record);
}