package  com.tl.resource.dao;

import com.tl.resource.dao.pojo.TForum;
import com.tl.resource.dao.pojo.TForumExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TForumDAOImpl extends SqlMapClientDaoSupport implements TForumDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public TForumDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int countByExample(TForumExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_forum.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int deleteByExample(TForumExample example) {
        int rows = getSqlMapClientTemplate().delete("t_forum.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        TForum key = new TForum();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_forum.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public void insert(TForum record) {
        getSqlMapClientTemplate().insert("t_forum.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public void insertSelective(TForum record) {
        getSqlMapClientTemplate().insert("t_forum.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public List selectByExampleWithBLOBs(TForumExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_forum.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public List selectByExampleWithoutBLOBs(TForumExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_forum.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public TForum selectByPrimaryKey(String id) {
        TForum key = new TForum();
        key.setId(id);
        TForum record = (TForum) getSqlMapClientTemplate().queryForObject("t_forum.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int updateByExampleSelective(TForum record, TForumExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_forum.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int updateByExampleWithBLOBs(TForum record, TForumExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_forum.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int updateByExampleWithoutBLOBs(TForum record, TForumExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_forum.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int updateByPrimaryKeySelective(TForum record) {
        int rows = getSqlMapClientTemplate().update("t_forum.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int updateByPrimaryKeyWithBLOBs(TForum record) {
        int rows = getSqlMapClientTemplate().update("t_forum.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    public int updateByPrimaryKeyWithoutBLOBs(TForum record) {
        int rows = getSqlMapClientTemplate().update("t_forum.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_forum
     *
     * @ibatorgenerated Sun Jan 20 13:35:44 CST 2013
     */
    private static class UpdateByExampleParms extends TForumExample {
        private Object record;

        public UpdateByExampleParms(Object record, TForumExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}