package  com.tl.resource.dao;

import com.tl.resource.dao.pojo.TForumPersons;
import com.tl.resource.dao.pojo.TForumPersonsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TForumPersonsDAOImpl extends SqlMapClientDaoSupport implements TForumPersonsDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public TForumPersonsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public int countByExample(TForumPersonsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_forum_persons.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public int deleteByExample(TForumPersonsExample example) {
        int rows = getSqlMapClientTemplate().delete("t_forum_persons.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        TForumPersons key = new TForumPersons();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_forum_persons.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public void insert(TForumPersons record) {
        getSqlMapClientTemplate().insert("t_forum_persons.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public void insertSelective(TForumPersons record) {
        getSqlMapClientTemplate().insert("t_forum_persons.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public List selectByExample(TForumPersonsExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_forum_persons.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public TForumPersons selectByPrimaryKey(String id) {
        TForumPersons key = new TForumPersons();
        key.setId(id);
        TForumPersons record = (TForumPersons) getSqlMapClientTemplate().queryForObject("t_forum_persons.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public int updateByExampleSelective(TForumPersons record, TForumPersonsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_forum_persons.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public int updateByExample(TForumPersons record, TForumPersonsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_forum_persons.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public int updateByPrimaryKeySelective(TForumPersons record) {
        int rows = getSqlMapClientTemplate().update("t_forum_persons.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    public int updateByPrimaryKey(TForumPersons record) {
        int rows = getSqlMapClientTemplate().update("t_forum_persons.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_forum_persons
     *
     * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
     */
    private static class UpdateByExampleParms extends TForumPersonsExample {
        private Object record;

        public UpdateByExampleParms(Object record, TForumPersonsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}