package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TMatReserveInfor;
import com.tl.resource.dao.pojo.TMatReserveInforExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TMatReserveInforDAOImpl extends SqlMapClientDaoSupport implements TMatReserveInforDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public TMatReserveInforDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void insert(TMatReserveInfor record) {
		getSqlMapClientTemplate().insert(
				"t_mat_reserve_infor.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public int updateByPrimaryKey(TMatReserveInfor record) {
		int rows = getSqlMapClientTemplate().update(
				"t_mat_reserve_infor.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public int updateByPrimaryKeySelective(TMatReserveInfor record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_mat_reserve_infor.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public List selectByExample(TMatReserveInforExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_mat_reserve_infor.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public TMatReserveInfor selectByPrimaryKey(String id) {
		TMatReserveInfor key = new TMatReserveInfor();
		key.setId(id);
		TMatReserveInfor record = (TMatReserveInfor) getSqlMapClientTemplate()
				.queryForObject(
						"t_mat_reserve_infor.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public int deleteByExample(TMatReserveInforExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_mat_reserve_infor.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public int deleteByPrimaryKey(String id) {
		TMatReserveInfor key = new TMatReserveInfor();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_mat_reserve_infor.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public int countByExample(TMatReserveInforExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_mat_reserve_infor.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public int updateByExampleSelective(TMatReserveInfor record,
			TMatReserveInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_mat_reserve_infor.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public int updateByExample(TMatReserveInfor record,
			TMatReserveInforExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_mat_reserve_infor.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_mat_reserve_infor
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private static class UpdateByExampleParms extends TMatReserveInforExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TMatReserveInforExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}