package com.tl.resource.dao;

import java.util.List;
import java.util.Map;

import com.tl.resource.business.dto.ArrivalOrderDetialsDto;
import com.tl.resource.business.dto.OrderDetialsDto;
import com.tl.resource.dao.pojo.TOrderDetail;
import com.tl.resource.dao.pojo.TOrderDetailExample;

public interface TOrderDetailDAO {

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  int countByExample(TOrderDetailExample example);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  int deleteByExample(TOrderDetailExample example);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  int deleteByPrimaryKey(String id);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  void insert(TOrderDetail record);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  void insertSelective(TOrderDetail record);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  List selectByExample(TOrderDetailExample example);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  TOrderDetail selectByPrimaryKey(String id);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  int updateByExampleSelective(TOrderDetail record, TOrderDetailExample example);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  int updateByExample(TOrderDetail record, TOrderDetailExample example);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  int updateByPrimaryKeySelective(TOrderDetail record);

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_order_detail
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  int updateByPrimaryKey(TOrderDetail record);

  /**
   * 根据订单得到订单详细
   * @param parmMap
   * @return
   */
  public List<OrderDetialsDto> getContractOrderDetailsListHasFileHasRemainAmount(Map<String, Object> parmMap);

  /**
   * 插入订单详细
   * @param orderDetail
   * @return
   */
  public OrderDetialsDto insertOrderDetail(OrderDetialsDto orderDetail);

  /**
   * 更新订单详细
   * @param orderDetail
   */
  public void updateOrderDetail(OrderDetialsDto orderDetail);

  /**
   * 根据ID删除订单
   * @param id
   */
  public void deleteByOrderId(String id);

  List<OrderDetialsDto> getOrderDetailsHasReserveInfor(String orderId);

  /**
   * 订单详细包含已经到货数量(ftl)2009-11-25
   * @param orderId
   * @return
   */
  public List<ArrivalOrderDetialsDto> getDetailWithHasArrivalByOrderId(String orderId);

  /**
   * 订单产品是否已全部到货 大于0 未全部到货（ftl)2009-12-07
   * @param orderId
   * @return
   */
  public Integer getCanArrivalPro(String orderId);

  public List<OrderDetialsDto> getOrderDetailsListsOfHasFileData(Map<String, Object> parmMap);

  /**
   * 合同订单详细
   * @param parmMap
   * @return
   */
  public List<OrderDetialsDto> getCOrderDetail(Map<String, Object> parmMap);

  /**
   * 订单详细列表(预定订单)
   * @param parmMap
   * @return
   */
  public List<OrderDetialsDto> getSOrderDetailList(Map<String, Object> parmMap);

  /**
   * 订单详细列表数量(预定订单)
   * @param parmMap
   * @return
   */
  public int getSOrderDetailListCount(Map<String, Object> parmMap);

  /**
   * 根据订单ID查找订单详细(预定加工订单详细)
   * @param contractId
   * @return
   */
  public List<OrderDetialsDto> getSSOrderDetailsList(Map<String, Object> parmMap);

  /**
   * 根据订单ID查找订单详细总数(预定加工订单详细)
   * @param contractId
   * @return
   */
  public int getSSOrderDetailsListCount(Map<String, Object> parmMap);

  /**
   * 合同订单 订单编制界面合同详细 产品列表
   * @param parmMap
   * @return
   */
  public List<OrderDetialsDto> selectOrderDetailFromContract(Map<String, Object> parmMap);

  /**
   * 合同订单 订单编制界面合同详细数量 产品列表
   * @param parmMap
   * @return
   */
  public int selectOrderDetailCountFromContract(Map<String, Object> parmMap);

  public List<OrderDetialsDto> getOrderDetailById(String id);

  /**
   * 比较订单与合同中采购价格，如果订单中高出，则返回订单详细的序号
   * @param orderInforId
   * @return
   */
  public List<TOrderDetail> cmprStockPrice(Map<String, Object> parmMap);

  Integer getNoEditPlanProductsCount(String orderInforId);

  void sycArrivalDetailOrderAmount(String orderId);
}