package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TOwnContactPerson;
import com.tl.resource.dao.pojo.TOwnContactPersonExample;
import java.util.List;
import java.util.Map;

public interface TOwnContactPersonDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    int countByExample(TOwnContactPersonExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    int deleteByExample(TOwnContactPersonExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    void insert(TOwnContactPerson record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    void insertSelective(TOwnContactPerson record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    List selectByExample(TOwnContactPersonExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    TOwnContactPerson selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    int updateByExampleSelective(TOwnContactPerson record, TOwnContactPersonExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    int updateByExample(TOwnContactPerson record, TOwnContactPersonExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    int updateByPrimaryKeySelective(TOwnContactPerson record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_own_contact_person
     *
     * @ibatorgenerated Mon Sep 13 09:49:07 CST 2010
     */
    int updateByPrimaryKey(TOwnContactPerson record);
    
    List<TOwnContactPerson> getWillSelectUser(Map<String, Object> parmMap);
    int getWillSelectUserCount(Map<String, Object> parmMap);
    List<TOwnContactPerson> getSelectedUser(Map<String, Object> parmMap);
}