package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TReservePlanMain;
import com.tl.resource.dao.pojo.TReservePlanMainExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TReservePlanMainDAOImpl extends SqlMapClientDaoSupport implements TReservePlanMainDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public TReservePlanMainDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public void insert(TReservePlanMain record) {
        getSqlMapClientTemplate().insert("t_reserve_plan_main.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public int updateByPrimaryKey(TReservePlanMain record) {
        int rows = getSqlMapClientTemplate().update("t_reserve_plan_main.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public int updateByPrimaryKeySelective(TReservePlanMain record) {
        int rows = getSqlMapClientTemplate().update("t_reserve_plan_main.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public List selectByExample(TReservePlanMainExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_reserve_plan_main.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public TReservePlanMain selectByPrimaryKey(String id) {
        TReservePlanMain key = new TReservePlanMain();
        key.setId(id);
        TReservePlanMain record = (TReservePlanMain) getSqlMapClientTemplate().queryForObject("t_reserve_plan_main.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public int deleteByExample(TReservePlanMainExample example) {
        int rows = getSqlMapClientTemplate().delete("t_reserve_plan_main.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public int deleteByPrimaryKey(String id) {
        TReservePlanMain key = new TReservePlanMain();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_reserve_plan_main.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public int countByExample(TReservePlanMainExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_reserve_plan_main.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public int updateByExampleSelective(TReservePlanMain record, TReservePlanMainExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_reserve_plan_main.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    public int updateByExample(TReservePlanMain record, TReservePlanMainExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_reserve_plan_main.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    private static class UpdateByExampleParms extends TReservePlanMainExample {
        private Object record;

        public UpdateByExampleParms(Object record, TReservePlanMainExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}