package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TReservePlanMain;
import com.tl.resource.dao.pojo.TReservePlanMainExample;
import java.util.List;

public interface TReservePlanMainDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    void insert(TReservePlanMain record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    int updateByPrimaryKey(TReservePlanMain record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    int updateByPrimaryKeySelective(TReservePlanMain record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    List selectByExample(TReservePlanMainExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    TReservePlanMain selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    int deleteByExample(TReservePlanMainExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    int countByExample(TReservePlanMainExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    int updateByExampleSelective(TReservePlanMain record, TReservePlanMainExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_reserve_plan_main
     *
     * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
     */
    int updateByExample(TReservePlanMain record, TReservePlanMainExample example);
}