package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TUserMessageRecord;
import com.tl.resource.dao.pojo.TUserMessageRecordExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TUserMessageRecordDAOImpl extends SqlMapClientDaoSupport implements TUserMessageRecordDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public TUserMessageRecordDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void insert(TUserMessageRecord record) {
		getSqlMapClientTemplate().insert(
				"t_user_message_record.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public int updateByPrimaryKey(TUserMessageRecord record) {
		int rows = getSqlMapClientTemplate().update(
				"t_user_message_record.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public int updateByPrimaryKeySelective(TUserMessageRecord record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"t_user_message_record.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public List selectByExample(TUserMessageRecordExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_user_message_record.abatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public TUserMessageRecord selectByPrimaryKey(String id) {
		TUserMessageRecord key = new TUserMessageRecord();
		key.setId(id);
		TUserMessageRecord record = (TUserMessageRecord) getSqlMapClientTemplate()
				.queryForObject(
						"t_user_message_record.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public int deleteByExample(TUserMessageRecordExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_user_message_record.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public int deleteByPrimaryKey(String id) {
		TUserMessageRecord key = new TUserMessageRecord();
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete(
						"t_user_message_record.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public int countByExample(TUserMessageRecordExample example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"t_user_message_record.abatorgenerated_countByExample",
						example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public int updateByExampleSelective(TUserMessageRecord record,
			TUserMessageRecordExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"t_user_message_record.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public int updateByExample(TUserMessageRecord record,
			TUserMessageRecordExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_user_message_record.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private static class UpdateByExampleParms extends TUserMessageRecordExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				TUserMessageRecordExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}