package com.tl.resource.dao;

import com.tl.resource.dao.pojo.TUserMessageRecord;
import com.tl.resource.dao.pojo.TUserMessageRecordExample;
import java.util.List;

public interface TUserMessageRecordDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	void insert(TUserMessageRecord record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	int updateByPrimaryKey(TUserMessageRecord record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	int updateByPrimaryKeySelective(TUserMessageRecord record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	List selectByExample(TUserMessageRecordExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	TUserMessageRecord selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	int deleteByExample(TUserMessageRecordExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	int countByExample(TUserMessageRecordExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	int updateByExampleSelective(TUserMessageRecord record,
			TUserMessageRecordExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	int updateByExample(TUserMessageRecord record,
			TUserMessageRecordExample example);
}