package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CompanyReportsExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public CompanyReportsExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    protected CompanyReportsExample(CompanyReportsExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table company_reports
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return this;
        }

        public Criteria andTitleIn(List values) {
            addCriterion("title in", values, "title");
            return this;
        }

        public Criteria andTitleNotIn(List values) {
            addCriterion("title not in", values, "title");
            return this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return this;
        }

        public Criteria andEditUserNameIsNull() {
            addCriterion("edit_user_name is null");
            return this;
        }

        public Criteria andEditUserNameIsNotNull() {
            addCriterion("edit_user_name is not null");
            return this;
        }

        public Criteria andEditUserNameEqualTo(String value) {
            addCriterion("edit_user_name =", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameNotEqualTo(String value) {
            addCriterion("edit_user_name <>", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameGreaterThan(String value) {
            addCriterion("edit_user_name >", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("edit_user_name >=", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameLessThan(String value) {
            addCriterion("edit_user_name <", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameLessThanOrEqualTo(String value) {
            addCriterion("edit_user_name <=", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameLike(String value) {
            addCriterion("edit_user_name like", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameNotLike(String value) {
            addCriterion("edit_user_name not like", value, "editUserName");
            return this;
        }

        public Criteria andEditUserNameIn(List values) {
            addCriterion("edit_user_name in", values, "editUserName");
            return this;
        }

        public Criteria andEditUserNameNotIn(List values) {
            addCriterion("edit_user_name not in", values, "editUserName");
            return this;
        }

        public Criteria andEditUserNameBetween(String value1, String value2) {
            addCriterion("edit_user_name between", value1, value2, "editUserName");
            return this;
        }

        public Criteria andEditUserNameNotBetween(String value1, String value2) {
            addCriterion("edit_user_name not between", value1, value2, "editUserName");
            return this;
        }

        public Criteria andEditDateIsNull() {
            addCriterion("edit_date is null");
            return this;
        }

        public Criteria andEditDateIsNotNull() {
            addCriterion("edit_date is not null");
            return this;
        }

        public Criteria andEditDateEqualTo(Date value) {
            addCriterion("edit_date =", value, "editDate");
            return this;
        }

        public Criteria andEditDateNotEqualTo(Date value) {
            addCriterion("edit_date <>", value, "editDate");
            return this;
        }

        public Criteria andEditDateGreaterThan(Date value) {
            addCriterion("edit_date >", value, "editDate");
            return this;
        }

        public Criteria andEditDateGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_date >=", value, "editDate");
            return this;
        }

        public Criteria andEditDateLessThan(Date value) {
            addCriterion("edit_date <", value, "editDate");
            return this;
        }

        public Criteria andEditDateLessThanOrEqualTo(Date value) {
            addCriterion("edit_date <=", value, "editDate");
            return this;
        }

        public Criteria andEditDateIn(List values) {
            addCriterion("edit_date in", values, "editDate");
            return this;
        }

        public Criteria andEditDateNotIn(List values) {
            addCriterion("edit_date not in", values, "editDate");
            return this;
        }

        public Criteria andEditDateBetween(Date value1, Date value2) {
            addCriterion("edit_date between", value1, value2, "editDate");
            return this;
        }

        public Criteria andEditDateNotBetween(Date value1, Date value2) {
            addCriterion("edit_date not between", value1, value2, "editDate");
            return this;
        }

        public Criteria andEditUserIdIsNull() {
            addCriterion("edit_user_id is null");
            return this;
        }

        public Criteria andEditUserIdIsNotNull() {
            addCriterion("edit_user_id is not null");
            return this;
        }

        public Criteria andEditUserIdEqualTo(String value) {
            addCriterion("edit_user_id =", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdNotEqualTo(String value) {
            addCriterion("edit_user_id <>", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdGreaterThan(String value) {
            addCriterion("edit_user_id >", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("edit_user_id >=", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdLessThan(String value) {
            addCriterion("edit_user_id <", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdLessThanOrEqualTo(String value) {
            addCriterion("edit_user_id <=", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdLike(String value) {
            addCriterion("edit_user_id like", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdNotLike(String value) {
            addCriterion("edit_user_id not like", value, "editUserId");
            return this;
        }

        public Criteria andEditUserIdIn(List values) {
            addCriterion("edit_user_id in", values, "editUserId");
            return this;
        }

        public Criteria andEditUserIdNotIn(List values) {
            addCriterion("edit_user_id not in", values, "editUserId");
            return this;
        }

        public Criteria andEditUserIdBetween(String value1, String value2) {
            addCriterion("edit_user_id between", value1, value2, "editUserId");
            return this;
        }

        public Criteria andEditUserIdNotBetween(String value1, String value2) {
            addCriterion("edit_user_id not between", value1, value2, "editUserId");
            return this;
        }
    }
}