package com.tl.resource.dao.pojo;

import java.util.Date;

public class CompanyReports {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column company_reports.id
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column company_reports.title
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column company_reports.edit_user_name
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    private String editUserName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column company_reports.edit_date
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    private Date editDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column company_reports.edit_user_id
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    private String editUserId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column company_reports.content
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    private String content;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column company_reports.id
     *
     * @return the value of company_reports.id
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column company_reports.id
     *
     * @param id the value for company_reports.id
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column company_reports.title
     *
     * @return the value of company_reports.title
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column company_reports.title
     *
     * @param title the value for company_reports.title
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column company_reports.edit_user_name
     *
     * @return the value of company_reports.edit_user_name
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public String getEditUserName() {
        return editUserName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column company_reports.edit_user_name
     *
     * @param editUserName the value for company_reports.edit_user_name
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void setEditUserName(String editUserName) {
        this.editUserName = editUserName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column company_reports.edit_date
     *
     * @return the value of company_reports.edit_date
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column company_reports.edit_date
     *
     * @param editDate the value for company_reports.edit_date
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column company_reports.edit_user_id
     *
     * @return the value of company_reports.edit_user_id
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column company_reports.edit_user_id
     *
     * @param editUserId the value for company_reports.edit_user_id
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column company_reports.content
     *
     * @return the value of company_reports.content
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column company_reports.content
     *
     * @param content the value for company_reports.content
     *
     * @abatorgenerated Sun Nov 18 08:57:10 GMT 2012
     */
    public void setContent(String content) {
        this.content = content;
    }
}