package com.tl.resource.dao.pojo;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class TCustomersInfor {
  private static final DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");

  public static final Integer MUST_HAVE_FILE = 1;//必须要附件

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.id
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String id;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.customer_degree_id
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String customerDegreeId;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.customer_name
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String customerName;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.customer_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String customerCode;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.customer_short_name
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String customerShortName;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.contact_person_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String contactPersonFirst;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.phone_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String phoneFirst;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.fax_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String faxFirst;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.contact_person_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String contactPersonSec;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.phone_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String phoneSec;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.fax_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String faxSec;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.own_contact_person
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String ownContactPerson;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.degree_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String degreeCode;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.contract_address
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String contractAddress;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.postcode
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String postcode;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.com_adress
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String comAdress;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.bank
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String bank;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.account_number
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String accountNumber;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.tax_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String taxCode;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.home_page
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String homePage;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.email
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String email;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_customers_infor.memo
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  private String memo;

  private String closingAccountMode;

  private BigDecimal reputationMoney;//信誉额度

  private Integer reputationPeriod;//信誉有效期

  private Integer lockStatus;

  /**
   * 客户信誉标准，1合同金额，2发票金额，3交货金额 
   */
  private Integer reputationType;

  private String ownContactPersonId;

  private String customerFixCode;

  private Date editDate;

  private Date lastUpdateDate;

  private String editDateString;

  private String lastUpdateDateString;

  private BigDecimal sumAccount;//付款金额

  private BigDecimal sumContractMoney;//合同金额

  private Integer qianKuanDay;//欠款天数

  private Date qianKuanDate;

  private String qianKuanDateString;

  private Date qianKuanOverDate;

  private String qianKuanOverDateString;

  private Integer contractRunCondi;//合同执行条件

  private Integer tryCutDoCondi;//是否可以做试刀

  private Integer scheduleDoCondi;//是否可以做预定

  public Integer getReputationType() {
    return reputationType;
  }

  public void setReputationType(Integer reputationType) {
    this.reputationType = reputationType;
  }

  public BigDecimal getReputationMoney() {
    return reputationMoney;
  }

  public void setReputationMoney(BigDecimal reputationMoney) {
    this.reputationMoney = reputationMoney;
  }

  public Integer getReputationPeriod() {
    return reputationPeriod;
  }

  public void setReputationPeriod(Integer reputationPeriod) {
    this.reputationPeriod = reputationPeriod;
  }

  public Integer getLockStatus() {
    return lockStatus;
  }

  public void setLockStatus(Integer lockStatus) {
    this.lockStatus = lockStatus;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.id
   * @return  the value of t_customers_infor.id
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.id
   * @param id  the value for t_customers_infor.id
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.customer_degree_id
   * @return  the value of t_customers_infor.customer_degree_id
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getCustomerDegreeId() {
    return customerDegreeId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.customer_degree_id
   * @param customerDegreeId  the value for t_customers_infor.customer_degree_id
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setCustomerDegreeId(String customerDegreeId) {
    this.customerDegreeId = customerDegreeId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.customer_name
   * @return  the value of t_customers_infor.customer_name
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getCustomerName() {
    return customerName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.customer_name
   * @param customerName  the value for t_customers_infor.customer_name
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.customer_code
   * @return  the value of t_customers_infor.customer_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getCustomerCode() {
    return customerCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.customer_code
   * @param customerCode  the value for t_customers_infor.customer_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setCustomerCode(String customerCode) {
    this.customerCode = customerCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.customer_short_name
   * @return  the value of t_customers_infor.customer_short_name
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getCustomerShortName() {
    return customerShortName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.customer_short_name
   * @param customerShortName  the value for t_customers_infor.customer_short_name
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setCustomerShortName(String customerShortName) {
    this.customerShortName = customerShortName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.contact_person_first
   * @return  the value of t_customers_infor.contact_person_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getContactPersonFirst() {
    return contactPersonFirst;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.contact_person_first
   * @param contactPersonFirst  the value for t_customers_infor.contact_person_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setContactPersonFirst(String contactPersonFirst) {
    this.contactPersonFirst = contactPersonFirst;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.phone_first
   * @return  the value of t_customers_infor.phone_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getPhoneFirst() {
    return phoneFirst;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.phone_first
   * @param phoneFirst  the value for t_customers_infor.phone_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setPhoneFirst(String phoneFirst) {
    this.phoneFirst = phoneFirst;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.fax_first
   * @return  the value of t_customers_infor.fax_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getFaxFirst() {
    return faxFirst;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.fax_first
   * @param faxFirst  the value for t_customers_infor.fax_first
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setFaxFirst(String faxFirst) {
    this.faxFirst = faxFirst;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.contact_person_sec
   * @return  the value of t_customers_infor.contact_person_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getContactPersonSec() {
    return contactPersonSec;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.contact_person_sec
   * @param contactPersonSec  the value for t_customers_infor.contact_person_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setContactPersonSec(String contactPersonSec) {
    this.contactPersonSec = contactPersonSec;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.phone_sec
   * @return  the value of t_customers_infor.phone_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getPhoneSec() {
    return phoneSec;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.phone_sec
   * @param phoneSec  the value for t_customers_infor.phone_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setPhoneSec(String phoneSec) {
    this.phoneSec = phoneSec;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.fax_sec
   * @return  the value of t_customers_infor.fax_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getFaxSec() {
    return faxSec;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.fax_sec
   * @param faxSec  the value for t_customers_infor.fax_sec
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setFaxSec(String faxSec) {
    this.faxSec = faxSec;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.own_contact_person
   * @return  the value of t_customers_infor.own_contact_person
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getOwnContactPerson() {
    return ownContactPerson;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.own_contact_person
   * @param ownContactPerson  the value for t_customers_infor.own_contact_person
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setOwnContactPerson(String ownContactPerson) {
    this.ownContactPerson = ownContactPerson;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.degree_code
   * @return  the value of t_customers_infor.degree_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getDegreeCode() {
    return degreeCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.degree_code
   * @param degreeCode  the value for t_customers_infor.degree_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setDegreeCode(String degreeCode) {
    this.degreeCode = degreeCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.contract_address
   * @return  the value of t_customers_infor.contract_address
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getContractAddress() {
    return contractAddress;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.contract_address
   * @param contractAddress  the value for t_customers_infor.contract_address
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.postcode
   * @return  the value of t_customers_infor.postcode
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getPostcode() {
    return postcode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.postcode
   * @param postcode  the value for t_customers_infor.postcode
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.com_adress
   * @return  the value of t_customers_infor.com_adress
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getComAdress() {
    return comAdress;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.com_adress
   * @param comAdress  the value for t_customers_infor.com_adress
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setComAdress(String comAdress) {
    this.comAdress = comAdress;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.bank
   * @return  the value of t_customers_infor.bank
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getBank() {
    return bank;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.bank
   * @param bank  the value for t_customers_infor.bank
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setBank(String bank) {
    this.bank = bank;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.account_number
   * @return  the value of t_customers_infor.account_number
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getAccountNumber() {
    return accountNumber;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.account_number
   * @param accountNumber  the value for t_customers_infor.account_number
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.tax_code
   * @return  the value of t_customers_infor.tax_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getTaxCode() {
    return taxCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.tax_code
   * @param taxCode  the value for t_customers_infor.tax_code
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setTaxCode(String taxCode) {
    this.taxCode = taxCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.home_page
   * @return  the value of t_customers_infor.home_page
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getHomePage() {
    return homePage;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.home_page
   * @param homePage  the value for t_customers_infor.home_page
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setHomePage(String homePage) {
    this.homePage = homePage;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.email
   * @return  the value of t_customers_infor.email
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getEmail() {
    return email;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.email
   * @param email  the value for t_customers_infor.email
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_customers_infor.memo
   * @return  the value of t_customers_infor.memo
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public String getMemo() {
    return memo;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_customers_infor.memo
   * @param memo  the value for t_customers_infor.memo
   * @ibatorgenerated  Wed Oct 14 14:13:27 CST 2009
   */
  public void setMemo(String memo) {
    this.memo = memo;
  }

  public String getOwnContactPersonId() {
    return ownContactPersonId;
  }

  public void setOwnContactPersonId(String ownContactPersonId) {
    this.ownContactPersonId = ownContactPersonId;
  }

  public String getClosingAccountMode() {
    return closingAccountMode;
  }

  public void setClosingAccountMode(String closingAccountMode) {
    this.closingAccountMode = closingAccountMode;
  }

  public String getCustomerFixCode() {
    //    if (this.customerCode == null || this.customerCode.length() < 1) {
    //      return "";
    //    }
    //    return this.customerCode.substring(0, 1);
    return this.customerFixCode;
  }

  public void setCustomerFixCode(String customerFixCode) {
    this.customerFixCode = customerFixCode;
  }

  public Date getEditDate() {
    return editDate;
  }

  public void setEditDate(Date editDate) {
    this.editDate = editDate;
  }

  public Date getLastUpdateDate() {
    return lastUpdateDate;
  }

  public void setLastUpdateDate(Date lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
  }

  public String getEditDateString() {
    if (this.editDate != null) {
      return df.format(this.editDate);
    }
    return editDateString;
  }

  public void setEditDateString(String editDateString) {
    this.editDateString = editDateString;
  }

  public String getLastUpdateDateString() {
    if (this.lastUpdateDate != null) {
      return df.format(this.lastUpdateDate);
    }
    return lastUpdateDateString;
  }

  public void setLastUpdateDateString(String lastUpdateDateString) {
    this.lastUpdateDateString = lastUpdateDateString;
  }

  public BigDecimal getSumAccount() {
    return sumAccount;
  }

  public void setSumAccount(BigDecimal sumAccount) {
    this.sumAccount = sumAccount;
  }

  public BigDecimal getSumContractMoney() {
    return sumContractMoney;
  }

  public void setSumContractMoney(BigDecimal sumContractMoney) {
    this.sumContractMoney = sumContractMoney;
  }

  public Integer getQianKuanDay() {
    //day = qianKuanOverDate - new Date();
    //qianKuanOverDate.
    if (qianKuanOverDate == null) {
      return 0;
    }
    return new Long((new Date().getTime() - qianKuanOverDate.getTime()) / 1000 / 60 / 60 / 24).intValue();
  }

  public void setQianKuanDay(Integer qianKuanDay) {
    this.qianKuanDay = qianKuanDay;
  }

  public Date getQianKuanDate() {
    return qianKuanDate;
  }

  public void setQianKuanDate(Date qianKuanDate) {
    this.qianKuanDate = qianKuanDate;
  }

  public String getQianKuanDateString() {
    if (this.qianKuanDate != null) {
      return df.format(this.qianKuanDate);
    }
    return qianKuanDateString;
  }

  public void setQianKuanDateString(String qianKuanDateString) {
    this.qianKuanDateString = qianKuanDateString;
  }

  public Date getQianKuanOverDate() {
    return qianKuanOverDate;
  }

  public void setQianKuanOverDate(Date qianKuanOverDate) {
    this.qianKuanOverDate = qianKuanOverDate;
  }

  public String getQianKuanOverDateString() {
    if (this.qianKuanOverDate != null) {
      return df.format(this.qianKuanOverDate);
    }
    return qianKuanOverDateString;
  }

  public void setQianKuanOverDateString(String qianKuanOverDateString) {
    this.qianKuanOverDateString = qianKuanOverDateString;
  }

  public Integer getContractRunCondi() {
    return contractRunCondi;
  }

  public void setContractRunCondi(Integer contractRunCondi) {
    this.contractRunCondi = contractRunCondi;
  }

  public Integer getTryCutDoCondi() {
    return tryCutDoCondi;
  }

  public void setTryCutDoCondi(Integer tryCutDoCondi) {
    this.tryCutDoCondi = tryCutDoCondi;
  }

  public Integer getScheduleDoCondi() {
    return scheduleDoCondi;
  }

  public void setScheduleDoCondi(Integer scheduleDoCondi) {
    this.scheduleDoCondi = scheduleDoCondi;
  }

}