package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TExpTempleteExample {

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  protected String orderByClause;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  protected List oredCriteria;

  private int startIndex;

  private int pageSize;

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public TExpTempleteExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  protected TExpTempleteExample(TExpTempleteExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Abator for iBATIS. This class corresponds to the database table t_exp_templete
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
        || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return this;
    }

    public Criteria andIdEqualTo(String value) {
      addCriterion("id =", value, "id");
      return this;
    }

    public Criteria andIdNotEqualTo(String value) {
      addCriterion("id <>", value, "id");
      return this;
    }

    public Criteria andIdGreaterThan(String value) {
      addCriterion("id >", value, "id");
      return this;
    }

    public Criteria andIdGreaterThanOrEqualTo(String value) {
      addCriterion("id >=", value, "id");
      return this;
    }

    public Criteria andIdLessThan(String value) {
      addCriterion("id <", value, "id");
      return this;
    }

    public Criteria andIdLessThanOrEqualTo(String value) {
      addCriterion("id <=", value, "id");
      return this;
    }

    public Criteria andIdLike(String value) {
      addCriterion("id like", value, "id");
      return this;
    }

    public Criteria andIdNotLike(String value) {
      addCriterion("id not like", value, "id");
      return this;
    }

    public Criteria andIdIn(List values) {
      addCriterion("id in", values, "id");
      return this;
    }

    public Criteria andIdNotIn(List values) {
      addCriterion("id not in", values, "id");
      return this;
    }

    public Criteria andIdBetween(String value1, String value2) {
      addCriterion("id between", value1, value2, "id");
      return this;
    }

    public Criteria andIdNotBetween(String value1, String value2) {
      addCriterion("id not between", value1, value2, "id");
      return this;
    }

    public Criteria andTempleteTypeIsNull() {
      addCriterion("templete_type is null");
      return this;
    }

    public Criteria andTempleteTypeIsNotNull() {
      addCriterion("templete_type is not null");
      return this;
    }

    public Criteria andTempleteTypeEqualTo(Integer value) {
      addCriterion("templete_type =", value, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeNotEqualTo(Integer value) {
      addCriterion("templete_type <>", value, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeGreaterThan(Integer value) {
      addCriterion("templete_type >", value, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeGreaterThanOrEqualTo(Integer value) {
      addCriterion("templete_type >=", value, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeLessThan(Integer value) {
      addCriterion("templete_type <", value, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeLessThanOrEqualTo(Integer value) {
      addCriterion("templete_type <=", value, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeIn(List values) {
      addCriterion("templete_type in", values, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeNotIn(List values) {
      addCriterion("templete_type not in", values, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeBetween(Integer value1, Integer value2) {
      addCriterion("templete_type between", value1, value2, "templeteType");
      return this;
    }

    public Criteria andTempleteTypeNotBetween(Integer value1, Integer value2) {
      addCriterion("templete_type not between", value1, value2, "templeteType");
      return this;
    }

    public Criteria andCreateTimeIsNull() {
      addCriterion("create_time is null");
      return this;
    }

    public Criteria andCreateTimeIsNotNull() {
      addCriterion("create_time is not null");
      return this;
    }

    public Criteria andCreateTimeEqualTo(Date value) {
      addCriterion("create_time =", value, "createTime");
      return this;
    }

    public Criteria andCreateTimeNotEqualTo(Date value) {
      addCriterion("create_time <>", value, "createTime");
      return this;
    }

    public Criteria andCreateTimeGreaterThan(Date value) {
      addCriterion("create_time >", value, "createTime");
      return this;
    }

    public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("create_time >=", value, "createTime");
      return this;
    }

    public Criteria andCreateTimeLessThan(Date value) {
      addCriterion("create_time <", value, "createTime");
      return this;
    }

    public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
      addCriterion("create_time <=", value, "createTime");
      return this;
    }

    public Criteria andCreateTimeIn(List values) {
      addCriterion("create_time in", values, "createTime");
      return this;
    }

    public Criteria andCreateTimeNotIn(List values) {
      addCriterion("create_time not in", values, "createTime");
      return this;
    }

    public Criteria andCreateTimeBetween(Date value1, Date value2) {
      addCriterion("create_time between", value1, value2, "createTime");
      return this;
    }

    public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
      addCriterion("create_time not between", value1, value2, "createTime");
      return this;
    }

    public Criteria andUserIdIsNull() {
      addCriterion("user_id is null");
      return this;
    }

    public Criteria andUserIdIsNotNull() {
      addCriterion("user_id is not null");
      return this;
    }

    public Criteria andUserIdEqualTo(String value) {
      addCriterion("user_id =", value, "userId");
      return this;
    }

    public Criteria andUserIdNotEqualTo(String value) {
      addCriterion("user_id <>", value, "userId");
      return this;
    }

    public Criteria andUserIdGreaterThan(String value) {
      addCriterion("user_id >", value, "userId");
      return this;
    }

    public Criteria andUserIdGreaterThanOrEqualTo(String value) {
      addCriterion("user_id >=", value, "userId");
      return this;
    }

    public Criteria andUserIdLessThan(String value) {
      addCriterion("user_id <", value, "userId");
      return this;
    }

    public Criteria andUserIdLessThanOrEqualTo(String value) {
      addCriterion("user_id <=", value, "userId");
      return this;
    }

    public Criteria andUserIdLike(String value) {
      addCriterion("user_id like", value, "userId");
      return this;
    }

    public Criteria andUserIdNotLike(String value) {
      addCriterion("user_id not like", value, "userId");
      return this;
    }

    public Criteria andUserIdIn(List values) {
      addCriterion("user_id in", values, "userId");
      return this;
    }

    public Criteria andUserIdNotIn(List values) {
      addCriterion("user_id not in", values, "userId");
      return this;
    }

    public Criteria andUserIdBetween(String value1, String value2) {
      addCriterion("user_id between", value1, value2, "userId");
      return this;
    }

    public Criteria andUserIdNotBetween(String value1, String value2) {
      addCriterion("user_id not between", value1, value2, "userId");
      return this;
    }

    public Criteria andUserNameIsNull() {
      addCriterion("user_name is null");
      return this;
    }

    public Criteria andUserNameIsNotNull() {
      addCriterion("user_name is not null");
      return this;
    }

    public Criteria andUserNameEqualTo(String value) {
      addCriterion("user_name =", value, "userName");
      return this;
    }

    public Criteria andUserNameNotEqualTo(String value) {
      addCriterion("user_name <>", value, "userName");
      return this;
    }

    public Criteria andUserNameGreaterThan(String value) {
      addCriterion("user_name >", value, "userName");
      return this;
    }

    public Criteria andUserNameGreaterThanOrEqualTo(String value) {
      addCriterion("user_name >=", value, "userName");
      return this;
    }

    public Criteria andUserNameLessThan(String value) {
      addCriterion("user_name <", value, "userName");
      return this;
    }

    public Criteria andUserNameLessThanOrEqualTo(String value) {
      addCriterion("user_name <=", value, "userName");
      return this;
    }

    public Criteria andUserNameLike(String value) {
      addCriterion("user_name like", value, "userName");
      return this;
    }

    public Criteria andUserNameNotLike(String value) {
      addCriterion("user_name not like", value, "userName");
      return this;
    }

    public Criteria andUserNameIn(List values) {
      addCriterion("user_name in", values, "userName");
      return this;
    }

    public Criteria andUserNameNotIn(List values) {
      addCriterion("user_name not in", values, "userName");
      return this;
    }

    public Criteria andUserNameBetween(String value1, String value2) {
      addCriterion("user_name between", value1, value2, "userName");
      return this;
    }

    public Criteria andUserNameNotBetween(String value1, String value2) {
      addCriterion("user_name not between", value1, value2, "userName");
      return this;
    }

    public Criteria andFileNameIsNull() {
      addCriterion("file_name is null");
      return this;
    }

    public Criteria andFileNameIsNotNull() {
      addCriterion("file_name is not null");
      return this;
    }

    public Criteria andFileNameEqualTo(String value) {
      addCriterion("file_name =", value, "fileName");
      return this;
    }

    public Criteria andFileNameNotEqualTo(String value) {
      addCriterion("file_name <>", value, "fileName");
      return this;
    }

    public Criteria andFileNameGreaterThan(String value) {
      addCriterion("file_name >", value, "fileName");
      return this;
    }

    public Criteria andFileNameGreaterThanOrEqualTo(String value) {
      addCriterion("file_name >=", value, "fileName");
      return this;
    }

    public Criteria andFileNameLessThan(String value) {
      addCriterion("file_name <", value, "fileName");
      return this;
    }

    public Criteria andFileNameLessThanOrEqualTo(String value) {
      addCriterion("file_name <=", value, "fileName");
      return this;
    }

    public Criteria andFileNameLike(String value) {
      addCriterion("file_name like", value, "fileName");
      return this;
    }

    public Criteria andFileNameNotLike(String value) {
      addCriterion("file_name not like", value, "fileName");
      return this;
    }

    public Criteria andFileNameIn(List values) {
      addCriterion("file_name in", values, "fileName");
      return this;
    }

    public Criteria andFileNameNotIn(List values) {
      addCriterion("file_name not in", values, "fileName");
      return this;
    }

    public Criteria andFileNameBetween(String value1, String value2) {
      addCriterion("file_name between", value1, value2, "fileName");
      return this;
    }

    public Criteria andFileNameNotBetween(String value1, String value2) {
      addCriterion("file_name not between", value1, value2, "fileName");
      return this;
    }

    public Criteria andFilePathIsNull() {
      addCriterion("file_path is null");
      return this;
    }

    public Criteria andFilePathIsNotNull() {
      addCriterion("file_path is not null");
      return this;
    }

    public Criteria andFilePathEqualTo(String value) {
      addCriterion("file_path =", value, "filePath");
      return this;
    }

    public Criteria andFilePathNotEqualTo(String value) {
      addCriterion("file_path <>", value, "filePath");
      return this;
    }

    public Criteria andFilePathGreaterThan(String value) {
      addCriterion("file_path >", value, "filePath");
      return this;
    }

    public Criteria andFilePathGreaterThanOrEqualTo(String value) {
      addCriterion("file_path >=", value, "filePath");
      return this;
    }

    public Criteria andFilePathLessThan(String value) {
      addCriterion("file_path <", value, "filePath");
      return this;
    }

    public Criteria andFilePathLessThanOrEqualTo(String value) {
      addCriterion("file_path <=", value, "filePath");
      return this;
    }

    public Criteria andFilePathLike(String value) {
      addCriterion("file_path like", value, "filePath");
      return this;
    }

    public Criteria andFilePathNotLike(String value) {
      addCriterion("file_path not like", value, "filePath");
      return this;
    }

    public Criteria andFilePathIn(List values) {
      addCriterion("file_path in", values, "filePath");
      return this;
    }

    public Criteria andFilePathNotIn(List values) {
      addCriterion("file_path not in", values, "filePath");
      return this;
    }

    public Criteria andFilePathBetween(String value1, String value2) {
      addCriterion("file_path between", value1, value2, "filePath");
      return this;
    }

    public Criteria andFilePathNotBetween(String value1, String value2) {
      addCriterion("file_path not between", value1, value2, "filePath");
      return this;
    }

    public Criteria andMemoIsNull() {
      addCriterion("memo is null");
      return this;
    }

    public Criteria andMemoIsNotNull() {
      addCriterion("memo is not null");
      return this;
    }

    public Criteria andMemoEqualTo(String value) {
      addCriterion("memo =", value, "memo");
      return this;
    }

    public Criteria andMemoNotEqualTo(String value) {
      addCriterion("memo <>", value, "memo");
      return this;
    }

    public Criteria andMemoGreaterThan(String value) {
      addCriterion("memo >", value, "memo");
      return this;
    }

    public Criteria andMemoGreaterThanOrEqualTo(String value) {
      addCriterion("memo >=", value, "memo");
      return this;
    }

    public Criteria andMemoLessThan(String value) {
      addCriterion("memo <", value, "memo");
      return this;
    }

    public Criteria andMemoLessThanOrEqualTo(String value) {
      addCriterion("memo <=", value, "memo");
      return this;
    }

    public Criteria andMemoLike(String value) {
      addCriterion("memo like", value, "memo");
      return this;
    }

    public Criteria andMemoNotLike(String value) {
      addCriterion("memo not like", value, "memo");
      return this;
    }

    public Criteria andMemoIn(List values) {
      addCriterion("memo in", values, "memo");
      return this;
    }

    public Criteria andMemoNotIn(List values) {
      addCriterion("memo not in", values, "memo");
      return this;
    }

    public Criteria andMemoBetween(String value1, String value2) {
      addCriterion("memo between", value1, value2, "memo");
      return this;
    }

    public Criteria andMemoNotBetween(String value1, String value2) {
      addCriterion("memo not between", value1, value2, "memo");
      return this;
    }

    public Criteria andDefaultTempIsNull() {
      addCriterion("default_temp is null");
      return this;
    }

    public Criteria andDefaultTempIsNotNull() {
      addCriterion("default_temp is not null");
      return this;
    }

    public Criteria andDefaultTempEqualTo(Integer value) {
      addCriterion("default_temp =", value, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempNotEqualTo(Integer value) {
      addCriterion("default_temp <>", value, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempGreaterThan(Integer value) {
      addCriterion("default_temp >", value, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempGreaterThanOrEqualTo(Integer value) {
      addCriterion("default_temp >=", value, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempLessThan(Integer value) {
      addCriterion("default_temp <", value, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempLessThanOrEqualTo(Integer value) {
      addCriterion("default_temp <=", value, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempIn(List values) {
      addCriterion("default_temp in", values, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempNotIn(List values) {
      addCriterion("default_temp not in", values, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempBetween(Integer value1, Integer value2) {
      addCriterion("default_temp between", value1, value2, "defaultTemp");
      return this;
    }

    public Criteria andDefaultTempNotBetween(Integer value1, Integer value2) {
      addCriterion("default_temp not between", value1, value2, "defaultTemp");
      return this;
    }

    public Criteria andTempleteNameIsNull() {
      addCriterion("templete_name is null");
      return this;
    }

    public Criteria andTempleteNameIsNotNull() {
      addCriterion("templete_name is not null");
      return this;
    }

    public Criteria andTempleteNameEqualTo(String value) {
      addCriterion("templete_name =", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameNotEqualTo(String value) {
      addCriterion("templete_name <>", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameGreaterThan(String value) {
      addCriterion("templete_name >", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameGreaterThanOrEqualTo(String value) {
      addCriterion("templete_name >=", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameLessThan(String value) {
      addCriterion("templete_name <", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameLessThanOrEqualTo(String value) {
      addCriterion("templete_name <=", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameLike(String value) {
      addCriterion("templete_name like", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameNotLike(String value) {
      addCriterion("templete_name not like", value, "templeteName");
      return this;
    }

    public Criteria andTempleteNameIn(List values) {
      addCriterion("templete_name in", values, "templeteName");
      return this;
    }

    public Criteria andTempleteNameNotIn(List values) {
      addCriterion("templete_name not in", values, "templeteName");
      return this;
    }

    public Criteria andTempleteNameBetween(String value1, String value2) {
      addCriterion("templete_name between", value1, value2, "templeteName");
      return this;
    }

    public Criteria andTempleteNameNotBetween(String value1, String value2) {
      addCriterion("templete_name not between", value1, value2, "templeteName");
      return this;
    }
  }

  public void setStartIndex(int startIndex) {
    // TODO Auto-generated method stub
    this.startIndex = startIndex;
  }

  public void setPageSize(int pageSize) {
    // TODO Auto-generated method stub
    this.pageSize = pageSize;
  }

  public int getStartIndex() {
    return startIndex;
  }

  public int getPageSize() {
    return pageSize;
  }

}