package com.tl.resource.dao.pojo;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class TExpTemplete {
  private static final DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.id
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private String id;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.templete_type
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private Integer templeteType;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.create_time
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private Date createTime;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.user_id
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private String userId;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.user_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private String userName;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.file_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private String fileName;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.file_path
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private String filePath;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.memo
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private String memo;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.default_temp
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private Integer defaultTemp;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column t_exp_templete.templete_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  private String templeteName;

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.id
   * @return  the value of t_exp_templete.id
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.id
   * @param id  the value for t_exp_templete.id
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.templete_type
   * @return  the value of t_exp_templete.templete_type
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public Integer getTempleteType() {
    return templeteType;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.templete_type
   * @param templeteType  the value for t_exp_templete.templete_type
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setTempleteType(Integer templeteType) {
    this.templeteType = templeteType;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.create_time
   * @return  the value of t_exp_templete.create_time
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.create_time
   * @param createTime  the value for t_exp_templete.create_time
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.user_id
   * @return  the value of t_exp_templete.user_id
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.user_id
   * @param userId  the value for t_exp_templete.user_id
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.user_name
   * @return  the value of t_exp_templete.user_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getUserName() {
    return userName;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.user_name
   * @param userName  the value for t_exp_templete.user_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.file_name
   * @return  the value of t_exp_templete.file_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getFileName() {
    return fileName;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.file_name
   * @param fileName  the value for t_exp_templete.file_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.file_path
   * @return  the value of t_exp_templete.file_path
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getFilePath() {
    return filePath;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.file_path
   * @param filePath  the value for t_exp_templete.file_path
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.memo
   * @return  the value of t_exp_templete.memo
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getMemo() {
    return memo;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.memo
   * @param memo  the value for t_exp_templete.memo
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setMemo(String memo) {
    this.memo = memo;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.default_temp
   * @return  the value of t_exp_templete.default_temp
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public Integer getDefaultTemp() {
    return defaultTemp;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.default_temp
   * @param defaultTemp  the value for t_exp_templete.default_temp
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setDefaultTemp(Integer defaultTemp) {
    this.defaultTemp = defaultTemp;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database column t_exp_templete.templete_name
   * @return  the value of t_exp_templete.templete_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public String getTempleteName() {
    return templeteName;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database column t_exp_templete.templete_name
   * @param templeteName  the value for t_exp_templete.templete_name
   * @abatorgenerated  Sun May 01 19:07:06 CST 2011
   */
  public void setTempleteName(String templeteName) {
    this.templeteName = templeteName;
  }

  public String getEditTimeString() {
    return df.format(this.getCreateTime());
  }
}
