package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TExpTempleteTypeExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public TExpTempleteTypeExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    protected TExpTempleteTypeExample(TExpTempleteTypeExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table t_exp_templete_type
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andTempTypeNameIsNull() {
            addCriterion("temp_type_name is null");
            return this;
        }

        public Criteria andTempTypeNameIsNotNull() {
            addCriterion("temp_type_name is not null");
            return this;
        }

        public Criteria andTempTypeNameEqualTo(String value) {
            addCriterion("temp_type_name =", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameNotEqualTo(String value) {
            addCriterion("temp_type_name <>", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameGreaterThan(String value) {
            addCriterion("temp_type_name >", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("temp_type_name >=", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameLessThan(String value) {
            addCriterion("temp_type_name <", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameLessThanOrEqualTo(String value) {
            addCriterion("temp_type_name <=", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameLike(String value) {
            addCriterion("temp_type_name like", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameNotLike(String value) {
            addCriterion("temp_type_name not like", value, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameIn(List values) {
            addCriterion("temp_type_name in", values, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameNotIn(List values) {
            addCriterion("temp_type_name not in", values, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameBetween(String value1, String value2) {
            addCriterion("temp_type_name between", value1, value2, "tempTypeName");
            return this;
        }

        public Criteria andTempTypeNameNotBetween(String value1, String value2) {
            addCriterion("temp_type_name not between", value1, value2, "tempTypeName");
            return this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return this;
        }

        public Criteria andClassNameIn(List values) {
            addCriterion("class_name in", values, "className");
            return this;
        }

        public Criteria andClassNameNotIn(List values) {
            addCriterion("class_name not in", values, "className");
            return this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return this;
        }
    }
}