package com.tl.resource.dao.pojo;

public class TExpTempleteType {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_exp_templete_type.id
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_exp_templete_type.temp_type_name
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    private String tempTypeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_exp_templete_type.class_name
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    private String className;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_exp_templete_type.id
     *
     * @return the value of t_exp_templete_type.id
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_exp_templete_type.id
     *
     * @param id the value for t_exp_templete_type.id
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_exp_templete_type.temp_type_name
     *
     * @return the value of t_exp_templete_type.temp_type_name
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public String getTempTypeName() {
        return tempTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_exp_templete_type.temp_type_name
     *
     * @param tempTypeName the value for t_exp_templete_type.temp_type_name
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public void setTempTypeName(String tempTypeName) {
        this.tempTypeName = tempTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_exp_templete_type.class_name
     *
     * @return the value of t_exp_templete_type.class_name
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_exp_templete_type.class_name
     *
     * @param className the value for t_exp_templete_type.class_name
     *
     * @abatorgenerated Mon May 02 19:59:23 CST 2011
     */
    public void setClassName(String className) {
        this.className = className;
    }
}