package com.tl.resource.dao.pojo;

public class TForumPersons {
  public static final Integer ACCEPT_PERSON_TYPE = 0;

  public static final Integer COPY_PERSON_TYPE = 1;

  public static final Integer INIT_STATUS = 0;

  public static final Integer RETURNED_STATUS = 1;

  /**
   * This field was generated by Apache iBATIS ibator.
   * This field corresponds to the database column t_forum_persons.id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  private String id;

  /**
   * This field was generated by Apache iBATIS ibator.
   * This field corresponds to the database column t_forum_persons.user_id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  private String userId;

  /**
   * This field was generated by Apache iBATIS ibator.
   * This field corresponds to the database column t_forum_persons.user_name
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  private String userName;

  /**
   * This field was generated by Apache iBATIS ibator.
   * This field corresponds to the database column t_forum_persons.forum_id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  private String forumId;

  /**
   * This field was generated by Apache iBATIS ibator.
   * This field corresponds to the database column t_forum_persons.pserson_type
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  private Integer psersonType;

  /**
   * This field was generated by Apache iBATIS ibator.
   * This field corresponds to the database column t_forum_persons.status
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  private Integer status;

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method returns the value of the database column t_forum_persons.id
   *
   * @return the value of t_forum_persons.id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method sets the value of the database column t_forum_persons.id
   *
   * @param id the value for t_forum_persons.id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method returns the value of the database column t_forum_persons.user_id
   *
   * @return the value of t_forum_persons.user_id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method sets the value of the database column t_forum_persons.user_id
   *
   * @param userId the value for t_forum_persons.user_id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method returns the value of the database column t_forum_persons.user_name
   *
   * @return the value of t_forum_persons.user_name
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public String getUserName() {
    return userName;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method sets the value of the database column t_forum_persons.user_name
   *
   * @param userName the value for t_forum_persons.user_name
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method returns the value of the database column t_forum_persons.forum_id
   *
   * @return the value of t_forum_persons.forum_id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public String getForumId() {
    return forumId;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method sets the value of the database column t_forum_persons.forum_id
   *
   * @param forumId the value for t_forum_persons.forum_id
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public void setForumId(String forumId) {
    this.forumId = forumId;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method returns the value of the database column t_forum_persons.pserson_type
   *
   * @return the value of t_forum_persons.pserson_type
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public Integer getPsersonType() {
    return psersonType;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method sets the value of the database column t_forum_persons.pserson_type
   *
   * @param psersonType the value for t_forum_persons.pserson_type
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public void setPsersonType(Integer psersonType) {
    this.psersonType = psersonType;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method returns the value of the database column t_forum_persons.status
   *
   * @return the value of t_forum_persons.status
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by Apache iBATIS ibator.
   * This method sets the value of the database column t_forum_persons.status
   *
   * @param status the value for t_forum_persons.status
   *
   * @ibatorgenerated Sat Jun 01 09:30:46 CST 2013
   */
  public void setStatus(Integer status) {
    this.status = status;
  }
}