package com.tl.resource.dao.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TMatAccountsInfor {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.reserve_infor_id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String reserveInforId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.reserve_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String reserveCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.account_type
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private Integer accountType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.invoice_id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String invoiceId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.invoice_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String invoiceCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.amount
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.price
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private BigDecimal price;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.money
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private BigDecimal money;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.brand_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String brandCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.product_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String productCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.product_name
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String productName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.product_unit
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String productUnit;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.product_brand
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String productBrand;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.product_source
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String productSource;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.currency_name
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private String currencyName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_mat_accounts_infor.create_account_time
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	private Date createAccountTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.id
	 * @return  the value of t_mat_accounts_infor.id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.id
	 * @param id  the value for t_mat_accounts_infor.id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.reserve_infor_id
	 * @return  the value of t_mat_accounts_infor.reserve_infor_id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getReserveInforId() {
		return reserveInforId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.reserve_infor_id
	 * @param reserveInforId  the value for t_mat_accounts_infor.reserve_infor_id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setReserveInforId(String reserveInforId) {
		this.reserveInforId = reserveInforId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.reserve_code
	 * @return  the value of t_mat_accounts_infor.reserve_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getReserveCode() {
		return reserveCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.reserve_code
	 * @param reserveCode  the value for t_mat_accounts_infor.reserve_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setReserveCode(String reserveCode) {
		this.reserveCode = reserveCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.account_type
	 * @return  the value of t_mat_accounts_infor.account_type
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public Integer getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.account_type
	 * @param accountType  the value for t_mat_accounts_infor.account_type
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setAccountType(Integer accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.invoice_id
	 * @return  the value of t_mat_accounts_infor.invoice_id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getInvoiceId() {
		return invoiceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.invoice_id
	 * @param invoiceId  the value for t_mat_accounts_infor.invoice_id
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.invoice_code
	 * @return  the value of t_mat_accounts_infor.invoice_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getInvoiceCode() {
		return invoiceCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.invoice_code
	 * @param invoiceCode  the value for t_mat_accounts_infor.invoice_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setInvoiceCode(String invoiceCode) {
		this.invoiceCode = invoiceCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.amount
	 * @return  the value of t_mat_accounts_infor.amount
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.amount
	 * @param amount  the value for t_mat_accounts_infor.amount
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.price
	 * @return  the value of t_mat_accounts_infor.price
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.price
	 * @param price  the value for t_mat_accounts_infor.price
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.money
	 * @return  the value of t_mat_accounts_infor.money
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public BigDecimal getMoney() {
		return money;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.money
	 * @param money  the value for t_mat_accounts_infor.money
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.brand_code
	 * @return  the value of t_mat_accounts_infor.brand_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getBrandCode() {
		return brandCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.brand_code
	 * @param brandCode  the value for t_mat_accounts_infor.brand_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setBrandCode(String brandCode) {
		this.brandCode = brandCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.product_code
	 * @return  the value of t_mat_accounts_infor.product_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.product_code
	 * @param productCode  the value for t_mat_accounts_infor.product_code
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.product_name
	 * @return  the value of t_mat_accounts_infor.product_name
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.product_name
	 * @param productName  the value for t_mat_accounts_infor.product_name
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.product_unit
	 * @return  the value of t_mat_accounts_infor.product_unit
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getProductUnit() {
		return productUnit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.product_unit
	 * @param productUnit  the value for t_mat_accounts_infor.product_unit
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setProductUnit(String productUnit) {
		this.productUnit = productUnit;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.product_brand
	 * @return  the value of t_mat_accounts_infor.product_brand
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getProductBrand() {
		return productBrand;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.product_brand
	 * @param productBrand  the value for t_mat_accounts_infor.product_brand
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setProductBrand(String productBrand) {
		this.productBrand = productBrand;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.product_source
	 * @return  the value of t_mat_accounts_infor.product_source
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getProductSource() {
		return productSource;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.product_source
	 * @param productSource  the value for t_mat_accounts_infor.product_source
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setProductSource(String productSource) {
		this.productSource = productSource;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.currency_name
	 * @return  the value of t_mat_accounts_infor.currency_name
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public String getCurrencyName() {
		return currencyName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.currency_name
	 * @param currencyName  the value for t_mat_accounts_infor.currency_name
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_mat_accounts_infor.create_account_time
	 * @return  the value of t_mat_accounts_infor.create_account_time
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public Date getCreateAccountTime() {
		return createAccountTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_mat_accounts_infor.create_account_time
	 * @param createAccountTime  the value for t_mat_accounts_infor.create_account_time
	 * @abatorgenerated  Sun Sep 11 15:45:49 CST 2011
	 */
	public void setCreateAccountTime(Date createAccountTime) {
		this.createAccountTime = createAccountTime;
	}
}