package com.tl.resource.dao.pojo;

import java.util.Date;

public class TReservePlanMain {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.id
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private String id;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.order_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private String orderCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.plan_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private String planCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.contract_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private String contractCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.edit_time
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private Date editTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.user_id
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private String userId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.user_name
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private String userName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.urgent_level
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private Integer urgentLevel;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column t_reserve_plan_main.memo
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	private String memo;

	private Integer status;

	private Integer planType;

	private String orderId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.id
	 * 
	 * @return the value of t_reserve_plan_main.id
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.id
	 * 
	 * @param id
	 *            the value for t_reserve_plan_main.id
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.order_code
	 * 
	 * @return the value of t_reserve_plan_main.order_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public String getOrderCode() {
		return orderCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.order_code
	 * 
	 * @param orderCode
	 *            the value for t_reserve_plan_main.order_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.plan_code
	 * 
	 * @return the value of t_reserve_plan_main.plan_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public String getPlanCode() {
		return planCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.plan_code
	 * 
	 * @param planCode
	 *            the value for t_reserve_plan_main.plan_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setPlanCode(String planCode) {
		this.planCode = planCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.contract_code
	 * 
	 * @return the value of t_reserve_plan_main.contract_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public String getContractCode() {
		return contractCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.contract_code
	 * 
	 * @param contractCode
	 *            the value for t_reserve_plan_main.contract_code
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setContractCode(String contractCode) {
		this.contractCode = contractCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.edit_time
	 * 
	 * @return the value of t_reserve_plan_main.edit_time
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public Date getEditTime() {
		return editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.edit_time
	 * 
	 * @param editTime
	 *            the value for t_reserve_plan_main.edit_time
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.user_id
	 * 
	 * @return the value of t_reserve_plan_main.user_id
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.user_id
	 * 
	 * @param userId
	 *            the value for t_reserve_plan_main.user_id
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.user_name
	 * 
	 * @return the value of t_reserve_plan_main.user_name
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.user_name
	 * 
	 * @param userName
	 *            the value for t_reserve_plan_main.user_name
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.urgent_level
	 * 
	 * @return the value of t_reserve_plan_main.urgent_level
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public Integer getUrgentLevel() {
		return urgentLevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.urgent_level
	 * 
	 * @param urgentLevel
	 *            the value for t_reserve_plan_main.urgent_level
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setUrgentLevel(Integer urgentLevel) {
		this.urgentLevel = urgentLevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column t_reserve_plan_main.memo
	 * 
	 * @return the value of t_reserve_plan_main.memo
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column t_reserve_plan_main.memo
	 * 
	 * @param memo
	 *            the value for t_reserve_plan_main.memo
	 * 
	 * @abatorgenerated Thu Aug 11 23:52:18 CST 2011
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getPlanType() {
		return planType;
	}

	public void setPlanType(Integer planType) {
		this.planType = planType;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

}