package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TReservePlanMainExample {
	private Integer startIndex;

	private Integer pageSize;

	public Integer getStartIndex() {
		return startIndex;
	}

	public void setStartIndex(Integer startIndex) {
		this.startIndex = startIndex;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public TReservePlanMainExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	protected TReservePlanMainExample(TReservePlanMainExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table t_reserve_plan_main
	 * 
	 * @abatorgenerated Sun Aug 21 17:36:50 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andOrderCodeIsNull() {
			addCriterion("order_code is null");
			return this;
		}

		public Criteria andOrderCodeIsNotNull() {
			addCriterion("order_code is not null");
			return this;
		}

		public Criteria andOrderCodeEqualTo(String value) {
			addCriterion("order_code =", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeNotEqualTo(String value) {
			addCriterion("order_code <>", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeGreaterThan(String value) {
			addCriterion("order_code >", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
			addCriterion("order_code >=", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeLessThan(String value) {
			addCriterion("order_code <", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeLessThanOrEqualTo(String value) {
			addCriterion("order_code <=", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeLike(String value) {
			addCriterion("order_code like", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeNotLike(String value) {
			addCriterion("order_code not like", value, "orderCode");
			return this;
		}

		public Criteria andOrderCodeIn(List values) {
			addCriterion("order_code in", values, "orderCode");
			return this;
		}

		public Criteria andOrderCodeNotIn(List values) {
			addCriterion("order_code not in", values, "orderCode");
			return this;
		}

		public Criteria andOrderCodeBetween(String value1, String value2) {
			addCriterion("order_code between", value1, value2, "orderCode");
			return this;
		}

		public Criteria andOrderCodeNotBetween(String value1, String value2) {
			addCriterion("order_code not between", value1, value2, "orderCode");
			return this;
		}

		public Criteria andPlanCodeIsNull() {
			addCriterion("plan_code is null");
			return this;
		}

		public Criteria andPlanCodeIsNotNull() {
			addCriterion("plan_code is not null");
			return this;
		}

		public Criteria andPlanCodeEqualTo(String value) {
			addCriterion("plan_code =", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeNotEqualTo(String value) {
			addCriterion("plan_code <>", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeGreaterThan(String value) {
			addCriterion("plan_code >", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeGreaterThanOrEqualTo(String value) {
			addCriterion("plan_code >=", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeLessThan(String value) {
			addCriterion("plan_code <", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeLessThanOrEqualTo(String value) {
			addCriterion("plan_code <=", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeLike(String value) {
			addCriterion("plan_code like", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeNotLike(String value) {
			addCriterion("plan_code not like", value, "planCode");
			return this;
		}

		public Criteria andPlanCodeIn(List values) {
			addCriterion("plan_code in", values, "planCode");
			return this;
		}

		public Criteria andPlanCodeNotIn(List values) {
			addCriterion("plan_code not in", values, "planCode");
			return this;
		}

		public Criteria andPlanCodeBetween(String value1, String value2) {
			addCriterion("plan_code between", value1, value2, "planCode");
			return this;
		}

		public Criteria andPlanCodeNotBetween(String value1, String value2) {
			addCriterion("plan_code not between", value1, value2, "planCode");
			return this;
		}

		public Criteria andContractCodeIsNull() {
			addCriterion("contract_code is null");
			return this;
		}

		public Criteria andContractCodeIsNotNull() {
			addCriterion("contract_code is not null");
			return this;
		}

		public Criteria andContractCodeEqualTo(String value) {
			addCriterion("contract_code =", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeNotEqualTo(String value) {
			addCriterion("contract_code <>", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeGreaterThan(String value) {
			addCriterion("contract_code >", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeGreaterThanOrEqualTo(String value) {
			addCriterion("contract_code >=", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeLessThan(String value) {
			addCriterion("contract_code <", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeLessThanOrEqualTo(String value) {
			addCriterion("contract_code <=", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeLike(String value) {
			addCriterion("contract_code like", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeNotLike(String value) {
			addCriterion("contract_code not like", value, "contractCode");
			return this;
		}

		public Criteria andContractCodeIn(List values) {
			addCriterion("contract_code in", values, "contractCode");
			return this;
		}

		public Criteria andContractCodeNotIn(List values) {
			addCriterion("contract_code not in", values, "contractCode");
			return this;
		}

		public Criteria andContractCodeBetween(String value1, String value2) {
			addCriterion("contract_code between", value1, value2,
					"contractCode");
			return this;
		}

		public Criteria andContractCodeNotBetween(String value1, String value2) {
			addCriterion("contract_code not between", value1, value2,
					"contractCode");
			return this;
		}

		public Criteria andEditTimeIsNull() {
			addCriterion("edit_time is null");
			return this;
		}

		public Criteria andEditTimeIsNotNull() {
			addCriterion("edit_time is not null");
			return this;
		}

		public Criteria andEditTimeEqualTo(Date value) {
			addCriterion("edit_time =", value, "editTime");
			return this;
		}

		public Criteria andEditTimeNotEqualTo(Date value) {
			addCriterion("edit_time <>", value, "editTime");
			return this;
		}

		public Criteria andEditTimeGreaterThan(Date value) {
			addCriterion("edit_time >", value, "editTime");
			return this;
		}

		public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("edit_time >=", value, "editTime");
			return this;
		}

		public Criteria andEditTimeLessThan(Date value) {
			addCriterion("edit_time <", value, "editTime");
			return this;
		}

		public Criteria andEditTimeLessThanOrEqualTo(Date value) {
			addCriterion("edit_time <=", value, "editTime");
			return this;
		}

		public Criteria andEditTimeIn(List values) {
			addCriterion("edit_time in", values, "editTime");
			return this;
		}

		public Criteria andEditTimeNotIn(List values) {
			addCriterion("edit_time not in", values, "editTime");
			return this;
		}

		public Criteria andEditTimeBetween(Date value1, Date value2) {
			addCriterion("edit_time between", value1, value2, "editTime");
			return this;
		}

		public Criteria andEditTimeNotBetween(Date value1, Date value2) {
			addCriterion("edit_time not between", value1, value2, "editTime");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("user_id in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("user_id not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return this;
		}

		public Criteria andUserNameIn(List values) {
			addCriterion("user_name in", values, "userName");
			return this;
		}

		public Criteria andUserNameNotIn(List values) {
			addCriterion("user_name not in", values, "userName");
			return this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return this;
		}

		public Criteria andUrgentLevelIsNull() {
			addCriterion("urgent_level is null");
			return this;
		}

		public Criteria andUrgentLevelIsNotNull() {
			addCriterion("urgent_level is not null");
			return this;
		}

		public Criteria andUrgentLevelEqualTo(Integer value) {
			addCriterion("urgent_level =", value, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelNotEqualTo(Integer value) {
			addCriterion("urgent_level <>", value, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelGreaterThan(Integer value) {
			addCriterion("urgent_level >", value, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("urgent_level >=", value, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelLessThan(Integer value) {
			addCriterion("urgent_level <", value, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelLessThanOrEqualTo(Integer value) {
			addCriterion("urgent_level <=", value, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelIn(List values) {
			addCriterion("urgent_level in", values, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelNotIn(List values) {
			addCriterion("urgent_level not in", values, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelBetween(Integer value1, Integer value2) {
			addCriterion("urgent_level between", value1, value2, "urgentLevel");
			return this;
		}

		public Criteria andUrgentLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("urgent_level not between", value1, value2,
					"urgentLevel");
			return this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return this;
		}

		public Criteria andMemoIn(List values) {
			addCriterion("memo in", values, "memo");
			return this;
		}

		public Criteria andMemoNotIn(List values) {
			addCriterion("memo not in", values, "memo");
			return this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("order_id =", value, "orderId");
			return this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("order_id <>", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("order_id >", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_id >=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("order_id <", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("order_id <=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("order_id like", value, "orderId");
			return this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("order_id not like", value, "orderId");
			return this;
		}

		public Criteria andOrderIdIn(List values) {
			addCriterion("order_id in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdNotIn(List values) {
			addCriterion("order_id not in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("status in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("status not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return this;
		}

		public Criteria andPlanTypeIsNull() {
			addCriterion("plan_type is null");
			return this;
		}

		public Criteria andPlanTypeIsNotNull() {
			addCriterion("plan_type is not null");
			return this;
		}

		public Criteria andPlanTypeEqualTo(Integer value) {
			addCriterion("plan_type =", value, "planType");
			return this;
		}

		public Criteria andPlanTypeNotEqualTo(Integer value) {
			addCriterion("plan_type <>", value, "planType");
			return this;
		}

		public Criteria andPlanTypeGreaterThan(Integer value) {
			addCriterion("plan_type >", value, "planType");
			return this;
		}

		public Criteria andPlanTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("plan_type >=", value, "planType");
			return this;
		}

		public Criteria andPlanTypeLessThan(Integer value) {
			addCriterion("plan_type <", value, "planType");
			return this;
		}

		public Criteria andPlanTypeLessThanOrEqualTo(Integer value) {
			addCriterion("plan_type <=", value, "planType");
			return this;
		}

		public Criteria andPlanTypeIn(List values) {
			addCriterion("plan_type in", values, "planType");
			return this;
		}

		public Criteria andPlanTypeNotIn(List values) {
			addCriterion("plan_type not in", values, "planType");
			return this;
		}

		public Criteria andPlanTypeBetween(Integer value1, Integer value2) {
			addCriterion("plan_type between", value1, value2, "planType");
			return this;
		}

		public Criteria andPlanTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("plan_type not between", value1, value2, "planType");
			return this;
		}
	}
}