package com.tl.resource.dao.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TUserMessageRecordExample {

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  protected String orderByClause;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  protected List oredCriteria;

  private int startIndex;

  private int pageSize;

  public int getStartIndex() {
    return startIndex;
  }

  public void setStartIndex(int startIndex) {
    this.startIndex = startIndex;
  }

  public int getPageSize() {
    return pageSize;
  }

  public void setPageSize(int pageSize) {
    this.pageSize = pageSize;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public TUserMessageRecordExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  protected TUserMessageRecordExample(TUserMessageRecordExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Abator for iBATIS. This method corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Abator for iBATIS. This class corresponds to the database table t_user_message_record
   * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0
        || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return this;
    }

    public Criteria andIdEqualTo(String value) {
      addCriterion("id =", value, "id");
      return this;
    }

    public Criteria andIdNotEqualTo(String value) {
      addCriterion("id <>", value, "id");
      return this;
    }

    public Criteria andIdGreaterThan(String value) {
      addCriterion("id >", value, "id");
      return this;
    }

    public Criteria andIdGreaterThanOrEqualTo(String value) {
      addCriterion("id >=", value, "id");
      return this;
    }

    public Criteria andIdLessThan(String value) {
      addCriterion("id <", value, "id");
      return this;
    }

    public Criteria andIdLessThanOrEqualTo(String value) {
      addCriterion("id <=", value, "id");
      return this;
    }

    public Criteria andIdLike(String value) {
      addCriterion("id like", value, "id");
      return this;
    }

    public Criteria andIdNotLike(String value) {
      addCriterion("id not like", value, "id");
      return this;
    }

    public Criteria andIdIn(List values) {
      addCriterion("id in", values, "id");
      return this;
    }

    public Criteria andIdNotIn(List values) {
      addCriterion("id not in", values, "id");
      return this;
    }

    public Criteria andIdBetween(String value1, String value2) {
      addCriterion("id between", value1, value2, "id");
      return this;
    }

    public Criteria andIdNotBetween(String value1, String value2) {
      addCriterion("id not between", value1, value2, "id");
      return this;
    }

    public Criteria andFromUserIdIsNull() {
      addCriterion("from_user_id is null");
      return this;
    }

    public Criteria andFromUserIdIsNotNull() {
      addCriterion("from_user_id is not null");
      return this;
    }

    public Criteria andFromUserIdEqualTo(String value) {
      addCriterion("from_user_id =", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdNotEqualTo(String value) {
      addCriterion("from_user_id <>", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdGreaterThan(String value) {
      addCriterion("from_user_id >", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdGreaterThanOrEqualTo(String value) {
      addCriterion("from_user_id >=", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdLessThan(String value) {
      addCriterion("from_user_id <", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdLessThanOrEqualTo(String value) {
      addCriterion("from_user_id <=", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdLike(String value) {
      addCriterion("from_user_id like", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdNotLike(String value) {
      addCriterion("from_user_id not like", value, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdIn(List values) {
      addCriterion("from_user_id in", values, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdNotIn(List values) {
      addCriterion("from_user_id not in", values, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdBetween(String value1, String value2) {
      addCriterion("from_user_id between", value1, value2, "fromUserId");
      return this;
    }

    public Criteria andFromUserIdNotBetween(String value1, String value2) {
      addCriterion("from_user_id not between", value1, value2, "fromUserId");
      return this;
    }

    public Criteria andFromUserNameIsNull() {
      addCriterion("from_user_name is null");
      return this;
    }

    public Criteria andFromUserNameIsNotNull() {
      addCriterion("from_user_name is not null");
      return this;
    }

    public Criteria andFromUserNameEqualTo(String value) {
      addCriterion("from_user_name =", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameNotEqualTo(String value) {
      addCriterion("from_user_name <>", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameGreaterThan(String value) {
      addCriterion("from_user_name >", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameGreaterThanOrEqualTo(String value) {
      addCriterion("from_user_name >=", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameLessThan(String value) {
      addCriterion("from_user_name <", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameLessThanOrEqualTo(String value) {
      addCriterion("from_user_name <=", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameLike(String value) {
      addCriterion("from_user_name like", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameNotLike(String value) {
      addCriterion("from_user_name not like", value, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameIn(List values) {
      addCriterion("from_user_name in", values, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameNotIn(List values) {
      addCriterion("from_user_name not in", values, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameBetween(String value1, String value2) {
      addCriterion("from_user_name between", value1, value2, "fromUserName");
      return this;
    }

    public Criteria andFromUserNameNotBetween(String value1, String value2) {
      addCriterion("from_user_name not between", value1, value2, "fromUserName");
      return this;
    }

    public Criteria andToUserIdIsNull() {
      addCriterion("to_user_id is null");
      return this;
    }

    public Criteria andToUserIdIsNotNull() {
      addCriterion("to_user_id is not null");
      return this;
    }

    public Criteria andToUserIdEqualTo(String value) {
      addCriterion("to_user_id =", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdNotEqualTo(String value) {
      addCriterion("to_user_id <>", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdGreaterThan(String value) {
      addCriterion("to_user_id >", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdGreaterThanOrEqualTo(String value) {
      addCriterion("to_user_id >=", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdLessThan(String value) {
      addCriterion("to_user_id <", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdLessThanOrEqualTo(String value) {
      addCriterion("to_user_id <=", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdLike(String value) {
      addCriterion("to_user_id like", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdNotLike(String value) {
      addCriterion("to_user_id not like", value, "toUserId");
      return this;
    }

    public Criteria andToUserIdIn(List values) {
      addCriterion("to_user_id in", values, "toUserId");
      return this;
    }

    public Criteria andToUserIdNotIn(List values) {
      addCriterion("to_user_id not in", values, "toUserId");
      return this;
    }

    public Criteria andToUserIdBetween(String value1, String value2) {
      addCriterion("to_user_id between", value1, value2, "toUserId");
      return this;
    }

    public Criteria andToUserIdNotBetween(String value1, String value2) {
      addCriterion("to_user_id not between", value1, value2, "toUserId");
      return this;
    }

    public Criteria andToUserNameIsNull() {
      addCriterion("to_user_name is null");
      return this;
    }

    public Criteria andToUserNameIsNotNull() {
      addCriterion("to_user_name is not null");
      return this;
    }

    public Criteria andToUserNameEqualTo(String value) {
      addCriterion("to_user_name =", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameNotEqualTo(String value) {
      addCriterion("to_user_name <>", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameGreaterThan(String value) {
      addCriterion("to_user_name >", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameGreaterThanOrEqualTo(String value) {
      addCriterion("to_user_name >=", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameLessThan(String value) {
      addCriterion("to_user_name <", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameLessThanOrEqualTo(String value) {
      addCriterion("to_user_name <=", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameLike(String value) {
      addCriterion("to_user_name like", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameNotLike(String value) {
      addCriterion("to_user_name not like", value, "toUserName");
      return this;
    }

    public Criteria andToUserNameIn(List values) {
      addCriterion("to_user_name in", values, "toUserName");
      return this;
    }

    public Criteria andToUserNameNotIn(List values) {
      addCriterion("to_user_name not in", values, "toUserName");
      return this;
    }

    public Criteria andToUserNameBetween(String value1, String value2) {
      addCriterion("to_user_name between", value1, value2, "toUserName");
      return this;
    }

    public Criteria andToUserNameNotBetween(String value1, String value2) {
      addCriterion("to_user_name not between", value1, value2, "toUserName");
      return this;
    }

    public Criteria andSendTimeIsNull() {
      addCriterion("send_time is null");
      return this;
    }

    public Criteria andSendTimeIsNotNull() {
      addCriterion("send_time is not null");
      return this;
    }

    public Criteria andSendTimeEqualTo(Date value) {
      addCriterion("send_time =", value, "sendTime");
      return this;
    }

    public Criteria andSendTimeNotEqualTo(Date value) {
      addCriterion("send_time <>", value, "sendTime");
      return this;
    }

    public Criteria andSendTimeGreaterThan(Date value) {
      addCriterion("send_time >", value, "sendTime");
      return this;
    }

    public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("send_time >=", value, "sendTime");
      return this;
    }

    public Criteria andSendTimeLessThan(Date value) {
      addCriterion("send_time <", value, "sendTime");
      return this;
    }

    public Criteria andSendTimeLessThanOrEqualTo(Date value) {
      addCriterion("send_time <=", value, "sendTime");
      return this;
    }

    public Criteria andSendTimeIn(List values) {
      addCriterion("send_time in", values, "sendTime");
      return this;
    }

    public Criteria andSendTimeNotIn(List values) {
      addCriterion("send_time not in", values, "sendTime");
      return this;
    }

    public Criteria andSendTimeBetween(Date value1, Date value2) {
      addCriterion("send_time between", value1, value2, "sendTime");
      return this;
    }

    public Criteria andSendTimeNotBetween(Date value1, Date value2) {
      addCriterion("send_time not between", value1, value2, "sendTime");
      return this;
    }

    public Criteria andMessageIsNull() {
      addCriterion("message is null");
      return this;
    }

    public Criteria andMessageIsNotNull() {
      addCriterion("message is not null");
      return this;
    }

    public Criteria andMessageEqualTo(String value) {
      addCriterion("message =", value, "message");
      return this;
    }

    public Criteria andMessageNotEqualTo(String value) {
      addCriterion("message <>", value, "message");
      return this;
    }

    public Criteria andMessageGreaterThan(String value) {
      addCriterion("message >", value, "message");
      return this;
    }

    public Criteria andMessageGreaterThanOrEqualTo(String value) {
      addCriterion("message >=", value, "message");
      return this;
    }

    public Criteria andMessageLessThan(String value) {
      addCriterion("message <", value, "message");
      return this;
    }

    public Criteria andMessageLessThanOrEqualTo(String value) {
      addCriterion("message <=", value, "message");
      return this;
    }

    public Criteria andMessageLike(String value) {
      addCriterion("message like", value, "message");
      return this;
    }

    public Criteria andMessageNotLike(String value) {
      addCriterion("message not like", value, "message");
      return this;
    }

    public Criteria andMessageIn(List values) {
      addCriterion("message in", values, "message");
      return this;
    }

    public Criteria andMessageNotIn(List values) {
      addCriterion("message not in", values, "message");
      return this;
    }

    public Criteria andMessageBetween(String value1, String value2) {
      addCriterion("message between", value1, value2, "message");
      return this;
    }

    public Criteria andMessageNotBetween(String value1, String value2) {
      addCriterion("message not between", value1, value2, "message");
      return this;
    }

    public Criteria andFromUserDepartIsNull() {
      addCriterion("from_user_depart is null");
      return this;
    }

    public Criteria andFromUserDepartIsNotNull() {
      addCriterion("from_user_depart is not null");
      return this;
    }

    public Criteria andFromUserDepartEqualTo(String value) {
      addCriterion("from_user_depart =", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartNotEqualTo(String value) {
      addCriterion("from_user_depart <>", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartGreaterThan(String value) {
      addCriterion("from_user_depart >", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartGreaterThanOrEqualTo(String value) {
      addCriterion("from_user_depart >=", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartLessThan(String value) {
      addCriterion("from_user_depart <", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartLessThanOrEqualTo(String value) {
      addCriterion("from_user_depart <=", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartLike(String value) {
      addCriterion("from_user_depart like", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartNotLike(String value) {
      addCriterion("from_user_depart not like", value, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartIn(List values) {
      addCriterion("from_user_depart in", values, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartNotIn(List values) {
      addCriterion("from_user_depart not in", values, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartBetween(String value1, String value2) {
      addCriterion("from_user_depart between", value1, value2, "fromUserDepart");
      return this;
    }

    public Criteria andFromUserDepartNotBetween(String value1, String value2) {
      addCriterion("from_user_depart not between", value1, value2, "fromUserDepart");
      return this;
    }

    public Criteria andToUserDepartIsNull() {
      addCriterion("to_user_depart is null");
      return this;
    }

    public Criteria andToUserDepartIsNotNull() {
      addCriterion("to_user_depart is not null");
      return this;
    }

    public Criteria andToUserDepartEqualTo(String value) {
      addCriterion("to_user_depart =", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartNotEqualTo(String value) {
      addCriterion("to_user_depart <>", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartGreaterThan(String value) {
      addCriterion("to_user_depart >", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartGreaterThanOrEqualTo(String value) {
      addCriterion("to_user_depart >=", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartLessThan(String value) {
      addCriterion("to_user_depart <", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartLessThanOrEqualTo(String value) {
      addCriterion("to_user_depart <=", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartLike(String value) {
      addCriterion("to_user_depart like", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartNotLike(String value) {
      addCriterion("to_user_depart not like", value, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartIn(List values) {
      addCriterion("to_user_depart in", values, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartNotIn(List values) {
      addCriterion("to_user_depart not in", values, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartBetween(String value1, String value2) {
      addCriterion("to_user_depart between", value1, value2, "toUserDepart");
      return this;
    }

    public Criteria andToUserDepartNotBetween(String value1, String value2) {
      addCriterion("to_user_depart not between", value1, value2, "toUserDepart");
      return this;
    }
  }
}