package com.tl.resource.dao.pojo;

import java.util.Date;

public class TUserMessageRecord {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.from_user_id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String fromUserId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.from_user_name
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String fromUserName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.to_user_id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String toUserId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.to_user_name
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String toUserName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.send_time
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private Date sendTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.message
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String message;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.from_user_depart
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String fromUserDepart;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column t_user_message_record.to_user_depart
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	private String toUserDepart;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.id
	 * @return  the value of t_user_message_record.id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.id
	 * @param id  the value for t_user_message_record.id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.from_user_id
	 * @return  the value of t_user_message_record.from_user_id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getFromUserId() {
		return fromUserId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.from_user_id
	 * @param fromUserId  the value for t_user_message_record.from_user_id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setFromUserId(String fromUserId) {
		this.fromUserId = fromUserId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.from_user_name
	 * @return  the value of t_user_message_record.from_user_name
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getFromUserName() {
		return fromUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.from_user_name
	 * @param fromUserName  the value for t_user_message_record.from_user_name
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.to_user_id
	 * @return  the value of t_user_message_record.to_user_id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getToUserId() {
		return toUserId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.to_user_id
	 * @param toUserId  the value for t_user_message_record.to_user_id
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setToUserId(String toUserId) {
		this.toUserId = toUserId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.to_user_name
	 * @return  the value of t_user_message_record.to_user_name
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getToUserName() {
		return toUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.to_user_name
	 * @param toUserName  the value for t_user_message_record.to_user_name
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.send_time
	 * @return  the value of t_user_message_record.send_time
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.send_time
	 * @param sendTime  the value for t_user_message_record.send_time
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.message
	 * @return  the value of t_user_message_record.message
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.message
	 * @param message  the value for t_user_message_record.message
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.from_user_depart
	 * @return  the value of t_user_message_record.from_user_depart
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getFromUserDepart() {
		return fromUserDepart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.from_user_depart
	 * @param fromUserDepart  the value for t_user_message_record.from_user_depart
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setFromUserDepart(String fromUserDepart) {
		this.fromUserDepart = fromUserDepart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column t_user_message_record.to_user_depart
	 * @return  the value of t_user_message_record.to_user_depart
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public String getToUserDepart() {
		return toUserDepart;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column t_user_message_record.to_user_depart
	 * @param toUserDepart  the value for t_user_message_record.to_user_depart
	 * @abatorgenerated  Wed Nov 02 22:06:36 CST 2011
	 */
	public void setToUserDepart(String toUserDepart) {
		this.toUserDepart = toUserDepart;
	}
}